### ISSUE TITLE
UniSkinMod for MC1.9.0 Private Server (F1934) Crashes

### ISSUE THREAD

**Issue by JonnyBrando** [RecursiveG/UniSkinMod#8]
What I gather:
Caused by: java.lang.RuntimeException: Attempted to load class org/devinprogress/uniskinmod/UniSkinMod for invalid side SERVER

The mod/transformer is only loaded client side (works fine in single player), but is not loaded server side.

No crash dump created.

Private Server Log:
[15:21:21] [main/TRACE] [FML/]: Registering transformer org.devinprogress.uniskinmod.coremod.AsmTransformer
[15:21:21] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:12]: java.lang.reflect.InvocationTargetException
[15:21:21] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:12]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:21:21] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:12]:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:21:21] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:12]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:21:21] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:12]:  at java.lang.reflect.Method.invoke(Method.java:498)
[15:21:21] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:12]:  at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[15:21:21] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:12]:  at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[15:21:21] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:48]: Caused by: java.lang.NoClassDefFoundError: org/devinprogress/uniskinmod/UniSkinMod
[15:21:21] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:48]:   at org.devinprogress.uniskinmod.coremod.AsmTransformer.<clinit>(AsmTransformer.java:11)
[15:21:21] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:48]:   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[15:21:21] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:48]:   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[15:21:21] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:48]:   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[15:21:21] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:48]:   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[15:21:21] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:48]:   at java.lang.Class.newInstance(Class.java:442)
[15:21:21] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:48]:   at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.<init>(ASMTransformerWrapper.java:218)
[15:21:21] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:48]:   at $wrapper.org.devinprogress.uniskinmod.coremod.AsmTransformer.<init>(Unknown Source)
[15:21:21] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:48]:   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[15:21:21] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:48]:   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[15:21:21] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:48]:   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[15:21:21] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:48]:   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[15:21:21] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:48]:   at java.lang.Class.newInstance(Class.java:442)
[15:21:21] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:48]:   at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
[15:21:21] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:48]:   at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:124)
[15:21:21] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:48]:   at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[15:21:21] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:48]:   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[15:21:21] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:48]:   ... 6 more
[15:21:21] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.ClassNotFoundException: org.devinprogress.uniskinmod.UniSkinMod
[15:21:21] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[15:21:21] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[15:21:21] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[15:21:21] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]:    ... 23 more
[15:21:21] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@6b7906b3 from coremod FMLCorePlugin
[15:21:21] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]:    at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:234)
[15:21:21] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]:    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[15:21:21] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]:    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[15:21:21] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]:    ... 25 more
[15:21:21] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: Caused by: java.lang.RuntimeException: Attempted to load class org/devinprogress/uniskinmod/UniSkinMod for invalid side SERVER
[15:21:21] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]:    at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:49)
[15:21:21] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]:    at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:230)
[15:21:21] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]:    ... 27 more

**Comment by RecursiveG** [comment]
You do not need to install this mod on server. Just install on the client side.
